const jwt = require('jsonwebtoken');
const JWT_SECRET = "HUzefaBinJunedDeveloper"


const middleAuth = (req, res, next) => {

    try {
        const token = req.header("Authorization");
        // console.log("token with Bearer -",eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjI0ZDJiMjFjNWNhZmU2ODEzNjU4MjAzIn0sImlhdCI6MTY0OTc0NDkwMSwiZXhwIjoxNjQ5NzQ1NDAxfQ.evHxRGIuZza5I0qfMz6GM36jJ5vyuTZdr02mA_IhoU0)
        if (!token) return res.status(403).send("Access denied.");
        const newToken = token.split(" ")[1];
        console.log("token Which Is Generated BY JWT -",newToken)
        const data = jwt.verify(newToken, JWT_SECRET);
        req.user = data.user;
        next();
    } catch (error) {
        res.status(403).send("Invalid token");
    }

    // const token = req.header("Authorization");
    // console.log(token)
    // console.log(token.split(" ")[1])
    // console.log("req", req)
    // const newToken = token.split(" ")[1];
    // console.log("only-JWT-Token", newToken)
    // console.log(token.split(" ")[1]);
    // if (!newToken) {
    //     res.status(400).send({ Error: "Invalid Token   okkkkk" });
    //     console.log(error)

    // }
    // try {
    //     const data = jwt.verify(newToken, JWT_SECRET);
    //     req.user = data.user;
    //     console.log("data", data);
    //     console.log("auth success");
    //     next();

    // } catch (error) {
    //     res.status(401).send({ Error: "Invalid Token ok 2222" });
    //     console.log(error)

    // }
}

module.exports = middleAuth;